server:
  port: 8084
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.41.6:3306/test?generateSimpleParameterMetadata=true&useUnicode=true&characterEncoding=utf8
    username: oraupdate
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: 127.0.0.1:order-service

com:
  daniel:
    name: Daniel
    age: 28
