spring:
  application:
    name: order-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.41.6:3306/test?generateSimpleParameterMetadata=true&useUnicode=true&characterEncoding=utf8
    username: oraupdate
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true